<?php

use App\Jobs\RunAutoGenerateDueInvoicesJob;
use App\Jobs\RunBillingReminderScanJob;
use App\Models\CentralSetting;
use App\Models\Role;
use App\Models\Tenant;
use App\Models\User;
use App\Services\Central\PlatformModuleCatalogService;
use App\Services\Central\SubscriptionPackageCatalogService;
use App\Services\Central\TenantModuleActivationService;
use App\Services\Central\TenantSubscriptionInvoiceService;
use App\Services\Central\TenantSubscriptionService;
use App\Services\Tirta\TirtaConnectionLifecycleService;
use Illuminate\Foundation\Inspiring;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Schedule;
use Illuminate\Support\Str;

Artisan::command('inspire', function () {
    $this->comment(Inspiring::quote());
})->purpose('Display an inspiring quote');

Artisan::command('central:make-super-admin {email} {--password=} {--name=Super Admin}', function () {
    if (tenancy()->initialized) {
        tenancy()->end();
    }

    $email = (string) $this->argument('email');
    $name = (string) $this->option('name');
    $password = (string) ($this->option('password') ?: Str::password(16));

    $user = User::query()->updateOrCreate(
        ['email' => $email],
        [
            'name' => $name,
            'password' => Hash::make($password),
        ]
    );

    if (\Illuminate\Support\Facades\Schema::hasTable('roles')) {
        $ownerRole = Role::query()->firstOrCreate(
            ['slug' => 'owner'],
            ['name' => 'Owner']
        );

        $user->forceFill([
            'role_id' => $ownerRole->getKey(),
            'is_active' => true,
        ])->save();
    }

    $this->info('Central super admin siap.');
    $this->line('Email: ' . $user->email);
    $this->line('Password: ' . $password);
})->purpose('Create/update central super admin user (central guard)');

Artisan::command('billing:auto-generate-due-invoices {--limit-per-tenant=}', function () {
    if (tenancy()->initialized) {
        tenancy()->end();
    }

    $limitPerTenant = $this->option('limit-per-tenant');
    $limitPerTenant = is_numeric($limitPerTenant) && (int) $limitPerTenant > 0
        ? (int) $limitPerTenant
        : null;

    $result = app(\App\Http\Controllers\Central\SuperAdminTenantController::class)
        ->generateDueInvoicesBatch($limitPerTenant, 'console');

    if (($result['generated_count'] ?? 0) === 0) {
        $this->comment('Belum ada invoice due yang perlu digenerate.');

        return;
    }

    $this->info(sprintf(
        '%d invoice berhasil digenerate untuk %d tenant.',
        (int) $result['generated_count'],
        (int) $result['tenant_count']
    ));

    foreach ((array) ($result['generated_invoices'] ?? []) as $tenantId => $invoiceNumbers) {
        $numbers = collect($invoiceNumbers)
            ->filter(fn ($invoiceNumber): bool => is_string($invoiceNumber) && $invoiceNumber !== '')
            ->implode(', ');

        $this->line(sprintf('%s: %s', $tenantId, $numbers));
    }
})->purpose('Auto-generate invoice due berdasarkan subscription tenant aktif');

Artisan::command('billing:scan-reminders', function () {
    if (tenancy()->initialized) {
        tenancy()->end();
    }

    $result = app(\App\Http\Controllers\Central\SuperAdminTenantController::class)
        ->scanBillingReminders('console');

    $this->info(sprintf(
        'Reminder scan selesai. %d overdue, %d subscription mau habis.',
        (int) ($result['overdue_count'] ?? 0),
        (int) ($result['expiring_soon_count'] ?? 0)
    ));

    foreach ((array) ($result['overdue_tenants'] ?? []) as $tenant) {
        $this->line(sprintf(
            '[OVERDUE] %s - %s',
            (string) ($tenant['tenant_id'] ?? '-'),
            (string) ($tenant['invoice_number'] ?? '-')
        ));
    }

    foreach ((array) ($result['expiring_soon_tenants'] ?? []) as $tenant) {
        $this->line(sprintf(
            '[EXPIRING] %s - %s',
            (string) ($tenant['tenant_id'] ?? '-'),
            (string) ($tenant['expires_at'] ?? '-')
        ));
    }
})->purpose('Scan tenant billing yang overdue dan subscription yang segera habis');

Artisan::command('subscription:sync-relational-catalogs {--platform=} ', function () {
    if (tenancy()->initialized) {
        tenancy()->end();
    }

    $platform = $this->option('platform');
    $platform = is_string($platform) && in_array($platform, CentralSetting::availablePlatformTypes(), true)
        ? $platform
        : null;

    /** @var PlatformModuleCatalogService $moduleService */
    $moduleService = app(PlatformModuleCatalogService::class);
    /** @var SubscriptionPackageCatalogService $packageService */
    $packageService = app(SubscriptionPackageCatalogService::class);

    if (! $moduleService->tablesExist() || ! $packageService->tablesExist()) {
        $this->error('Tabel relasional subscription belum ada. Jalankan migrasi central dulu.');

        return;
    }

    $moduleService->syncFromLegacyCatalog(CentralSetting::legacyModuleCatalog());
    $packageService->syncFromLegacySettings($platform);

    $this->info('Sync katalog modul dan package ke tabel relasional selesai.');
})->purpose('Sync legacy module/package catalog ke tabel relasional subscription-aware');

Artisan::command('subscription:sync-tenant-runtime', function () {
    if (tenancy()->initialized) {
        tenancy()->end();
    }

    /** @var TenantSubscriptionService $subscriptionService */
    $subscriptionService = app(TenantSubscriptionService::class);
    /** @var TenantModuleActivationService $moduleActivationService */
    $moduleActivationService = app(TenantModuleActivationService::class);

    if (! $subscriptionService->tablesExist() || ! $moduleActivationService->tablesExist()) {
        $this->error('Tabel tenant subscription/module states belum ada. Jalankan migrasi central fase 2 dulu.');

        return;
    }

    $subscriptionService->syncAllFromLegacy();
    $moduleActivationService->syncAllFromLegacy();

    $this->info('Sync tenant subscription dan module states ke schema relasional selesai.');
})->purpose('Sync metadata tenant legacy ke tenant_subscriptions dan tenant_module_states');

Artisan::command('subscription:sync-tenant-invoices', function () {
    if (tenancy()->initialized) {
        tenancy()->end();
    }

    /** @var TenantSubscriptionInvoiceService $invoiceService */
    $invoiceService = app(TenantSubscriptionInvoiceService::class);

    if (! $invoiceService->tablesExist()) {
        $this->error('Tabel tenant subscription invoices belum ada. Jalankan migrasi central fase 4 dulu.');

        return;
    }

    $invoiceService->syncAllFromLegacy();

    $this->info('Sync invoice subscription tenant ke schema relasional selesai.');
})->purpose('Sync billing_invoices tenant legacy ke tenant_subscription_invoices relasional');

Artisan::command('subscription:audit-tenant-invoices {--tenant=} {--cleanup-shadow}', function () {
    if (tenancy()->initialized) {
        tenancy()->end();
    }

    /** @var TenantSubscriptionInvoiceService $invoiceService */
    $invoiceService = app(TenantSubscriptionInvoiceService::class);
    $tenantId = trim((string) $this->option('tenant'));
    $cleanupShadow = (bool) $this->option('cleanup-shadow');
    $report = $invoiceService->auditTenants($tenantId !== '' ? $tenantId : null);

    $this->info(sprintf(
        'Audit invoice tenant selesai. total=%d, relational_only=%d, relational_shadow=%d, legacy_only=%d, mismatch=%d, empty=%d',
        (int) data_get($report, 'counts.tenants', 0),
        (int) data_get($report, 'counts.relational_only', 0),
        (int) data_get($report, 'counts.relational_shadow', 0),
        (int) data_get($report, 'counts.legacy_only', 0),
        (int) data_get($report, 'counts.mismatch', 0),
        (int) data_get($report, 'counts.empty', 0)
    ));

    if (! (bool) data_get($report, 'tables_exist', false)) {
        $this->warn('Schema relasional invoice belum ada. Semua tenant saat ini masih fallback ke legacy.');
    }

    $cleanedCount = 0;

    foreach ((array) data_get($report, 'rows', []) as $row) {
        $line = sprintf(
            '%s | %s | rel=%d | legacy=%d | cleanup=%s',
            (string) ($row['tenant_id'] ?? '-'),
            (string) ($row['label'] ?? '-'),
            (int) ($row['relational_count'] ?? 0),
            (int) ($row['legacy_count'] ?? 0),
            (bool) ($row['cleanup_ready'] ?? false) ? 'ready' : 'no'
        );

        $legacyMetaKeys = collect((array) ($row['legacy_meta_keys'] ?? []))->implode(', ');
        if ($legacyMetaKeys !== '') {
            $line .= ' | meta=' . $legacyMetaKeys;
        }

        $mismatchInvoices = collect((array) ($row['mismatch_invoice_numbers'] ?? []))->take(5)->implode(', ');
        if ($mismatchInvoices !== '') {
            $line .= ' | mismatch=' . $mismatchInvoices;
        }

        $this->line($line);

        if (! $cleanupShadow || ! (bool) ($row['cleanup_ready'] ?? false)) {
            continue;
        }

        $tenant = Tenant::query()->find((string) ($row['tenant_id'] ?? ''));

        if (! $tenant) {
            continue;
        }

        $cleanup = $invoiceService->cleanupLegacyShadow($tenant);

        if ((bool) ($cleanup['cleaned'] ?? false)) {
            $cleanedCount++;
        }
    }

    if ($cleanupShadow) {
        $this->info(sprintf('Cleanup shadow legacy selesai. %d tenant dibersihkan.', $cleanedCount));
    }
})->purpose('Audit health invoice tenant legacy vs relasional, opsional cleanup shadow legacy yang sudah aman');

Artisan::command('tirta:audit-disconnections {--tenant=}', function () {
    if (tenancy()->initialized) {
        tenancy()->end();
    }

    $tenantId = trim((string) $this->option('tenant'));

    $query = Tenant::query()
        ->when($tenantId !== '', fn ($q) => $q->whereKey($tenantId))
        ->where('saas_type', 'tirta');

    $tenants = $query->get();

    if ($tenants->isEmpty()) {
        $this->comment('Tidak ada tenant Tirta yang cocok.');

        return;
    }

    /** @var TirtaConnectionLifecycleService $lifecycle */
    $lifecycle = app(TirtaConnectionLifecycleService::class);
    $totalDisconnected = 0;
    $totalScanned = 0;

    foreach ($tenants as $tenant) {
        tenancy()->initialize($tenant);

        /** @var \Modules\BaseFeature\Models\TenantSetting $setting */
        $setting = \Modules\BaseFeature\Models\TenantSetting::query()->firstOrCreate(
            [],
            [
                'brand_name' => (string) ($tenant->name ?? $tenant->id ?? config('app.name')),
                'description' => 'Workspace Tirta belum dikustomisasi.',
                'theme_color' => '#0891b2',
            ]
        );

        $report = $lifecycle->auditAndDisconnectOverdueConnections($setting, now());
        $totalDisconnected += (int) ($report['disconnected'] ?? 0);
        $totalScanned += (int) ($report['scanned'] ?? 0);

        $this->line(sprintf(
            '%s | scanned=%d | disconnected=%d | threshold=%d months',
            (string) $tenant->getKey(),
            (int) ($report['scanned'] ?? 0),
            (int) ($report['disconnected'] ?? 0),
            (int) ($report['threshold_months'] ?? 3)
        ));

        tenancy()->end();
    }

    $this->info(sprintf('Audit cabut Tirta selesai. total_scanned=%d total_disconnected=%d', $totalScanned, $totalDisconnected));
})->purpose('Audit sambungan Tirta yang menunggak dan otomatis cabut setelah ambang bulan');

Artisan::command('subscription:repair-tenant-invoices {--tenant=} {--mode=auto} {--cleanup-shadow}', function () {
    if (tenancy()->initialized) {
        tenancy()->end();
    }

    /** @var TenantSubscriptionInvoiceService $invoiceService */
    $invoiceService = app(TenantSubscriptionInvoiceService::class);
    $tenantId = trim((string) $this->option('tenant'));
    $mode = trim((string) $this->option('mode'));
    $cleanupShadow = (bool) $this->option('cleanup-shadow');
    $query = Tenant::query()->orderBy('id');

    if ($tenantId !== '') {
        $query->whereKey($tenantId);
    }

    $tenants = $query->get();

    if ($tenants->isEmpty()) {
        $this->warn('Tenant target tidak ditemukan untuk repair invoice.');

        return;
    }

    $resultCounts = [
        'synced' => 0,
        'cleaned' => 0,
        'skipped' => 0,
    ];

    foreach ($tenants as $tenant) {
        $result = $invoiceService->repairTenantInvoices($tenant, $mode, $cleanupShadow);
        $action = (string) ($result['action'] ?? 'skipped');

        if (str_contains($action, 'synced')) {
            $resultCounts['synced']++;
        }

        if (str_contains($action, 'cleaned')) {
            $resultCounts['cleaned']++;
        }

        if ($action === 'skipped') {
            $resultCounts['skipped']++;
        }

        $this->line(sprintf(
            '%s | %s -> %s | action=%s | reason=%s',
            (string) ($result['tenant_id'] ?? $tenant->getKey()),
            (string) data_get($result, 'before.label', '-'),
            (string) data_get($result, 'after.label', '-'),
            $action,
            (string) ($result['reason'] ?? '-')
        ));
    }

    $this->info(sprintf(
        'Repair invoice tenant selesai. synced=%d, cleaned=%d, skipped=%d',
        $resultCounts['synced'],
        $resultCounts['cleaned'],
        $resultCounts['skipped']
    ));
})->purpose('Repair atau backfill invoice tenant antar layer legacy dan relasional dengan mode aman');

$automationSettings = CentralSetting::automationSettings();

Schedule::job(new RunAutoGenerateDueInvoicesJob())
    ->dailyAt((string) ($automationSettings['billing_auto_generate_time'] ?? '00:10'))
    ->when(fn (): bool => (bool) ($automationSettings['billing_auto_generate_enabled'] ?? true))
    ->withoutOverlapping();

Schedule::job(new RunBillingReminderScanJob())
    ->dailyAt((string) ($automationSettings['billing_reminder_scan_time'] ?? '08:00'))
    ->when(fn (): bool => (bool) ($automationSettings['billing_reminder_scan_enabled'] ?? true))
    ->withoutOverlapping();

Schedule::command('tirta:audit-disconnections')
    ->dailyAt('01:10')
    ->withoutOverlapping();
