<?php

use App\Jobs\RunAutoGenerateDueInvoicesJob;
use App\Jobs\RunBillingReminderScanJob;
use App\Models\CentralSetting;
use App\Models\Role;
use App\Models\User;
use Illuminate\Foundation\Inspiring;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Schedule;
use Illuminate\Support\Str;

Artisan::command('inspire', function () {
    $this->comment(Inspiring::quote());
})->purpose('Display an inspiring quote');

Artisan::command('central:make-super-admin {email} {--password=} {--name=Super Admin}', function () {
    if (tenancy()->initialized) {
        tenancy()->end();
    }

    $email = (string) $this->argument('email');
    $name = (string) $this->option('name');
    $password = (string) ($this->option('password') ?: Str::password(16));

    $user = User::query()->updateOrCreate(
        ['email' => $email],
        [
            'name' => $name,
            'password' => Hash::make($password),
        ]
    );

    if (\Illuminate\Support\Facades\Schema::hasTable('roles')) {
        $ownerRole = Role::query()->firstOrCreate(
            ['slug' => 'owner'],
            ['name' => 'Owner']
        );

        $user->forceFill([
            'role_id' => $ownerRole->getKey(),
            'is_active' => true,
        ])->save();
    }

    $this->info('Central super admin siap.');
    $this->line('Email: ' . $user->email);
    $this->line('Password: ' . $password);
})->purpose('Create/update central super admin user (central guard)');

Artisan::command('billing:auto-generate-due-invoices {--limit-per-tenant=}', function () {
    if (tenancy()->initialized) {
        tenancy()->end();
    }

    $limitPerTenant = $this->option('limit-per-tenant');
    $limitPerTenant = is_numeric($limitPerTenant) && (int) $limitPerTenant > 0
        ? (int) $limitPerTenant
        : null;

    $result = app(\App\Http\Controllers\Central\SuperAdminTenantController::class)
        ->generateDueInvoicesBatch($limitPerTenant, 'console');

    if (($result['generated_count'] ?? 0) === 0) {
        $this->comment('Belum ada invoice due yang perlu digenerate.');

        return;
    }

    $this->info(sprintf(
        '%d invoice berhasil digenerate untuk %d tenant.',
        (int) $result['generated_count'],
        (int) $result['tenant_count']
    ));

    foreach ((array) ($result['generated_invoices'] ?? []) as $tenantId => $invoiceNumbers) {
        $numbers = collect($invoiceNumbers)
            ->filter(fn ($invoiceNumber): bool => is_string($invoiceNumber) && $invoiceNumber !== '')
            ->implode(', ');

        $this->line(sprintf('%s: %s', $tenantId, $numbers));
    }
})->purpose('Auto-generate invoice due berdasarkan subscription tenant aktif');

Artisan::command('billing:scan-reminders', function () {
    if (tenancy()->initialized) {
        tenancy()->end();
    }

    $result = app(\App\Http\Controllers\Central\SuperAdminTenantController::class)
        ->scanBillingReminders('console');

    $this->info(sprintf(
        'Reminder scan selesai. %d overdue, %d subscription mau habis.',
        (int) ($result['overdue_count'] ?? 0),
        (int) ($result['expiring_soon_count'] ?? 0)
    ));

    foreach ((array) ($result['overdue_tenants'] ?? []) as $tenant) {
        $this->line(sprintf(
            '[OVERDUE] %s - %s',
            (string) ($tenant['tenant_id'] ?? '-'),
            (string) ($tenant['invoice_number'] ?? '-')
        ));
    }

    foreach ((array) ($result['expiring_soon_tenants'] ?? []) as $tenant) {
        $this->line(sprintf(
            '[EXPIRING] %s - %s',
            (string) ($tenant['tenant_id'] ?? '-'),
            (string) ($tenant['expires_at'] ?? '-')
        ));
    }
})->purpose('Scan tenant billing yang overdue dan subscription yang segera habis');

$automationSettings = CentralSetting::automationSettings();

Schedule::job(new RunAutoGenerateDueInvoicesJob())
    ->dailyAt((string) ($automationSettings['billing_auto_generate_time'] ?? '00:10'))
    ->when(fn (): bool => (bool) ($automationSettings['billing_auto_generate_enabled'] ?? true))
    ->withoutOverlapping();

Schedule::job(new RunBillingReminderScanJob())
    ->dailyAt((string) ($automationSettings['billing_reminder_scan_time'] ?? '08:00'))
    ->when(fn (): bool => (bool) ($automationSettings['billing_reminder_scan_enabled'] ?? true))
    ->withoutOverlapping();
