<?php

declare(strict_types=1);

namespace App\Jobs;

use App\Http\Controllers\Central\SuperAdminTenantController;
use App\Services\Central\CentralAuditLogger;

class RunAutoGenerateDueInvoicesJob extends CentralAwareJob
{
    public function handle(SuperAdminTenantController $controller, CentralAuditLogger $auditLogger): void
    {
        $result = $controller->generateDueInvoicesBatch(null, 'queue');

        $auditLogger->info(
            'billing.auto_generate_queued',
            'Auto-generate due invoices dijalankan dari queue.',
            [
                'target_type' => 'billing',
                'target_id' => 'auto-generate',
                'meta' => [
                    'generated_count' => (int) ($result['generated_count'] ?? 0),
                    'tenant_count' => (int) ($result['tenant_count'] ?? 0),
                ],
            ]
        );
    }
}
